INSERT INTO GESTOR_DATABASE.USUARIOS
            (numero_identificacion,
             nombre,
             apellidos,
             direccion,
             numero_direccion,
             piso,
             puerta,
             municipio,
             provincia,
             codigo_postal,
             movil,
             telefono,
             email,
             cuenta_bancaria,
             usuario,
             contrasenya,
             sesion)
VALUES     ('28694057Q',
            'Antonio',
            'González Rodríguez',
            'Paseo de los Tristes',
            3,
            0,
            '',
            'Granada',
            'Andalucía',
            38005,
            '+34955738947',
            '+34694784087',
            'antonio@gmail.com',
            'ES6621000418401234567891',
            'antonio',
            '1234',
            false);
INSERT INTO GESTOR_DATABASE.USUARIOS
            (numero_identificacion,
             nombre,
             apellidos,
             direccion,
             numero_direccion,
             piso,
             puerta,
             municipio,
             provincia,
             codigo_postal,
             movil,
             telefono,
             email,
             cuenta_bancaria,
             usuario,
             contrasenya,
             sesion)
VALUES     ('96047395Q',
            'María del Carmen',
            'Gómez Fernández',
            'Calleja de las Flores',
            8,
            0,
            '',
            'Córdoba',
            'Andalucía',
            38005,
            '+34955738947',
            '+34694784087',
            'maria.carmen@outlook.com',
            '',
            'maria',
            '0987',
            false);
INSERT INTO GESTOR_DATABASE.USUARIOS
            (numero_identificacion,
             nombre,
             apellidos,
             direccion,
             numero_direccion,
             piso,
             puerta,
             municipio,
             provincia,
             codigo_postal,
             movil,
             telefono,
             email,
             cuenta_bancaria,
             usuario,
             contrasenya,
             sesion)
VALUES     ('72303849Z',
            'Jose',
            'López Díaz',
            'Calle Bétis',
            6,
            0,
            '',
            'Sevilla',
            'Andalucía',
            38005,
            '+34694784087',
            '+34955738947',
            'jose.lopez@gmx.es',
            'ES6000491500051234567892',
            'jose',
            '5678',
            false);