--
-- Este script resume los demás scripts de populación.
-- Cada sentencia SQL debe estar en una línea separada y ocupar solo una línea
--

--------------
-- CLIENTES --
--------------
INSERT INTO GESTOR_DATABASE.CLIENTES (numero_identificacion, nombre, apellidos, direccion, numero_direccion, piso, puerta, municipio, provincia, codigo_postal, movil, telefono, email, cuenta_bancaria) VALUES ('28694057Q', 'Antonio', 'González Rodríguez', 'Paseo de los Tristes', 3, 0, '', 'Granada', 'Andalucía', 18070, '+34955738947', '+34694784087', 'antonio@gmail.com', 'ES6621000418401234567891');
INSERT INTO GESTOR_DATABASE.CLIENTES (numero_identificacion, nombre, apellidos, direccion, numero_direccion, piso, puerta, municipio, provincia, codigo_postal, movil, telefono, email, cuenta_bancaria) VALUES ('96047395Q', 'María del Carmen', 'Gómez Fernández', 'Calleja de las Flores', 8, 0, '', 'Córdoba', 'Andalucía', 14001, '+34955738947', '+34694784087', 'maria.carmen@outlook.com', '');
INSERT INTO GESTOR_DATABASE.CLIENTES (numero_identificacion, nombre, apellidos, direccion, numero_direccion, piso, puerta, municipio, provincia, codigo_postal, movil, telefono, email, cuenta_bancaria) VALUES ('72303849Z', 'Jose', 'López Díaz', 'Calle Bétis', 6, 0, '', 'Sevilla', 'Andalucía', 41001, '+34694784087', '+34955738947', 'jose.lopez@gmx.es', 'ES6000491500051234567892');
INSERT INTO GESTOR_DATABASE.CLIENTES (numero_identificacion, nombre, apellidos, direccion, numero_direccion, piso, puerta, municipio, provincia, codigo_postal, movil, telefono, email, cuenta_bancaria) VALUES ('48945746K', 'Isabel', 'Martínez Perez', 'Gran Vía', 108, 0, '', 'Madrid', 'Madrid', 28001, '+34694784087', '+34955738947', 'isabel87@hotmail.com', 'ES9420805801101234567891');
INSERT INTO GESTOR_DATABASE.CLIENTES (numero_identificacion, nombre, apellidos, direccion, numero_direccion, piso, puerta, municipio, provincia, codigo_postal, movil, telefono, email, cuenta_bancaria) VALUES ('74849404K', 'Manuel', 'García Sánchez', 'Calle de los Ciegos', 20, 0, '', 'Jerez de la Frontera', 'Andalucía', 11401, '+34694784087', '+34955738947', 'manuelito@gmail.com', '');
INSERT INTO GESTOR_DATABASE.CLIENTES (numero_identificacion, nombre, apellidos, direccion, numero_direccion, piso, puerta, municipio, provincia, codigo_postal, movil, telefono, email, cuenta_bancaria) VALUES ('88337746J', 'Laura', 'Romero Sosa', 'Rúa do Franco', 7, 3, 'b', 'Santiago de Compostela', 'Galicia', 15701, '+34694784087', '+34955738947', '', '');
INSERT INTO GESTOR_DATABASE.CLIENTES (numero_identificacion, nombre, apellidos, direccion, numero_direccion, piso, puerta, municipio, provincia, codigo_postal, movil, telefono, email, cuenta_bancaria) VALUES ('83905867G', 'Francisco', 'Torres Álvarez', 'Calle Larios', 4, 0, '', 'Malaga', 'Andalucía', 29001, '+34694784087', '+34955738947', 'francisco.torres@gmail.com', 'ES7100302053091234567895');
INSERT INTO GESTOR_DATABASE.CLIENTES (numero_identificacion, nombre, apellidos, direccion, numero_direccion, piso, puerta, municipio, provincia, codigo_postal, movil, telefono, email, cuenta_bancaria) VALUES ('96867564M', 'Ana', 'Ruiz Ramirez', 'Calle Alcalá', 3, 2, 'a', 'Madrid', 'Madrid', 28001, '+34694784087', '+34955738947', '', 'ES1000492352082414205416');
INSERT INTO GESTOR_DATABASE.CLIENTES (numero_identificacion, nombre, apellidos, direccion, numero_direccion, piso, puerta, municipio, provincia, codigo_postal, movil, telefono, email, cuenta_bancaria) VALUES ('99588466F', 'David', 'Flores Benítez', 'Paseo de Gracia', 27, 0, '', 'Barcelona', 'Cataluña', 08001, '+34694784087', '+34955738947', 'david.flores@outlook.es', 'ES1720852066623456789011');

---------------
-- PRODUCTOS --
---------------
INSERT INTO GESTOR_DATABASE.PRODUCTOS (codigo_barras, nombre, marca, categoria, descripcion, precio_venta, cantidad) VALUES ('300239', 'Pijama polar hombre', 'Admas', 'pijama', '100% poliéster', 9.99, 30);
INSERT INTO GESTOR_DATABASE.PRODUCTOS (codigo_barras, nombre, marca, categoria, descripcion, precio_venta, cantidad) VALUES ('305733', 'Zapatillas hombre', 'Hanro', 'calzado', 'Plantilla acolchada.', 3.99, 15);
INSERT INTO GESTOR_DATABASE.PRODUCTOS (codigo_barras, nombre, marca, categoria, descripcion, precio_venta, cantidad) VALUES ('319351', 'Cama plegable', 'Pikolin', 'cama', 'Cama plegable fácil y rápida de montar.', 59.99, 5);
INSERT INTO GESTOR_DATABASE.PRODUCTOS (codigo_barras, nombre, marca, categoria, descripcion, precio_venta, cantidad) VALUES ('8406946830683', 'Almohada con relleno termoaislante 45 x 90 cm', 'Thinsulate', 'almohada', '', 9.99, 1);
INSERT INTO GESTOR_DATABASE.PRODUCTOS (codigo_barras, nombre, marca, categoria, descripcion, precio_venta, cantidad) VALUES ('8475078368509', 'Sábana bajera ajustable de franela para cama de 150 cm', 'Faustin', 'ropa de cama', 'Sábana bajera ajustable que proporciona suavidad y calidez gracias al algodón puro.', 9.99, 10);
INSERT INTO GESTOR_DATABASE.PRODUCTOS (codigo_barras, nombre, marca, categoria, descripcion, precio_venta, cantidad) VALUES ('8473524930478', 'Almohada con relleno termoaislante 45 x 75 cm', 'Thinsulate', 'almohada', 'Destaca por su exclusiva combinación de fibras que absorben y retienen el calor corporal.', 8.99, 10);
INSERT INTO GESTOR_DATABASE.PRODUCTOS (codigo_barras, nombre, marca, categoria, descripcion, precio_venta, cantidad) VALUES ('308263', 'Manta 150 x 200 cm', 'Pikolin', 'ropa de cama', 'Manta de microfibra de alta calidad con reverso muy suave.', 5.99, 5);

-----------------
-- PROVEEDORES --
-----------------
INSERT INTO GESTOR_DATABASE.PROVEEDORES (numero_identificacion, nombre, apellidos, direccion, numero_direccion, piso, puerta, municipio, provincia, codigo_postal, movil, telefono, email, cuenta_bancaria) VALUES ('A15075062', 'INDUSTRIA DE DISEÑO TEXTIL SA', '', 'Avenida De La Diputación', 3, 0, '', 'Arteixo', 'La Coruña', 15142, '', '+34981185400', '', '');
INSERT INTO GESTOR_DATABASE.PROVEEDORES (numero_identificacion, nombre, apellidos, direccion, numero_direccion, piso, puerta, municipio, provincia, codigo_postal, movil, telefono, email, cuenta_bancaria) VALUES ('A81948077', 'ENDESA ENERGIA SA', '', 'Calle Ribera Del Loira', 60, 0, '', 'Madrid', 'Madrid', 28042, '', '+34912131000', '', '');
INSERT INTO GESTOR_DATABASE.PROVEEDORES (numero_identificacion, nombre, apellidos, direccion, numero_direccion, piso, puerta, municipio, provincia, codigo_postal, movil, telefono, email, cuenta_bancaria) VALUES ('B59088948', 'PUNTO FA SL', '', 'Calle Mercaders', 9, 0, '', 'Palau-solita I Plegamans', 'Barcelona', 08184, '', '+34938602207', '', '');
INSERT INTO GESTOR_DATABASE.PROVEEDORES (numero_identificacion, nombre, apellidos, direccion, numero_direccion, piso, puerta, municipio, provincia, codigo_postal, movil, telefono, email, cuenta_bancaria) VALUES ('48945746K', 'ZARA ESPAÑA SA', '', 'Avenida De La Diputación ', 0, 0, '', 'Arteixo', 'La Coruña', 15142, '', '+34900814676', '', '');
INSERT INTO GESTOR_DATABASE.PROVEEDORES (numero_identificacion, nombre, apellidos, direccion, numero_direccion, piso, puerta, municipio, provincia, codigo_postal, movil, telefono, email, cuenta_bancaria) VALUES ('A15108673', 'PULL & BEAR ESPAÑA SA', '', 'Avenida De La Diputación', 20, 0, '', 'Arteixo', 'La Coruña', 15142, '', '+34900811822', '', '');
INSERT INTO GESTOR_DATABASE.PROVEEDORES (numero_identificacion, nombre, apellidos, direccion, numero_direccion, piso, puerta, municipio, provincia, codigo_postal, movil, telefono, email, cuenta_bancaria) VALUES ('B83875427', 'PRIMARK TIENDAS SL', '', 'Carretera Torrejón-ajalvir', 0, 0, '', 'Barrio De El Castillo', 'Madrid', 15701, '', '+34916600186', '', '');
INSERT INTO GESTOR_DATABASE.PROVEEDORES (numero_identificacion, nombre, apellidos, direccion, numero_direccion, piso, puerta, municipio, provincia, codigo_postal, movil, telefono, email, cuenta_bancaria) VALUES ('A78276854', 'BERSHKA BSK ESPAÑA SA', '', 'Avenida Diputación', 0, 0, '', 'Arteixo', 'La Coruña', 15142, '', '+34900456003', '', '');
INSERT INTO GESTOR_DATABASE.PROVEEDORES (numero_identificacion, nombre, apellidos, direccion, numero_direccion, piso, puerta, municipio, provincia, codigo_postal, movil, telefono, email, cuenta_bancaria) VALUES ('A59308114', 'SAMSUNG ELECTRONICS IBERIA SA', '', 'Avenida De Barajas', 32, 0, '', 'Parque Empresarial La Moraleja', 'Madrid', 28108, '', '+34902879081', '', '');

--------------
-- USUARIOS --
--------------
INSERT INTO GESTOR_DATABASE.USUARIOS (numero_identificacion, nombre, apellidos, direccion, numero_direccion, piso, puerta, municipio, provincia, codigo_postal, movil, telefono, email, cuenta_bancaria, usuario, contrasenya, sesion) VALUES ('28694057Q', 'Antonio', 'González Rodríguez', 'Paseo de los Tristes', 3, 0, '', 'Granada', 'Andalucía', 38005, '+34955738947', '+34694784087', 'antonio@gmail.com', 'ES6621000418401234567891', 'antonio', '1234', false);
INSERT INTO GESTOR_DATABASE.USUARIOS (numero_identificacion, nombre, apellidos, direccion, numero_direccion, piso, puerta, municipio, provincia, codigo_postal, movil, telefono, email, cuenta_bancaria, usuario, contrasenya, sesion) VALUES ('96047395Q', 'María del Carmen', 'Gómez Fernández', 'Calleja de las Flores', 8, 0, '', 'Córdoba', 'Andalucía', 38005, '+34955738947', '+34694784087', 'maria.carmen@outlook.com', '', 'maria', '0987', false);
INSERT INTO GESTOR_DATABASE.USUARIOS (numero_identificacion, nombre, apellidos, direccion, numero_direccion, piso, puerta, municipio, provincia, codigo_postal, movil, telefono, email, cuenta_bancaria, usuario, contrasenya, sesion) VALUES ('72303849Z', 'Jose', 'López Díaz', 'Calle Bétis', 6, 0, '', 'Sevilla', 'Andalucía', 38005, '+34694784087', '+34955738947', 'jose.lopez@gmx.es', 'ES6000491500051234567892', 'jose', '5678', false);