INSERT INTO GESTOR_DATABASE.CLIENTES
            (numero_identificacion,
             nombre,
             apellidos,
             direccion,
             numero_direccion,
             piso,
             puerta,
             municipio,
             provincia,
             codigo_postal,
             movil,
             telefono,
             email,
             cuenta_bancaria)
VALUES     ('28694057Q',
            'Antonio',
            'González Rodríguez',
            'Paseo de los Tristes',
            3,
            0,
            '',
            'Granada',
            'Andalucía',
            18070,
            '+34955738947',
            '+34694784087',
            'antonio@gmail.com',
            'ES6621000418401234567891');
INSERT INTO GESTOR_DATABASE.CLIENTES
            (numero_identificacion,
             nombre,
             apellidos,
             direccion,
             numero_direccion,
             piso,
             puerta,
             municipio,
             provincia,
             codigo_postal,
             movil,
             telefono,
             email,
             cuenta_bancaria)
VALUES     ('96047395-Q',
            'María del Carmen',
            'Gómez Fernández',
            'Calleja de las Flores',
            8,
            0,
            '',
            'Córdoba',
            'Andalucía',
            14001,
            '+34955738947',
            '+34694784087',
            'maria.carmen@outlook.com',
            '');
INSERT INTO GESTOR_DATABASE.CLIENTES
            (numero_identificacion,
             nombre,
             apellidos,
             direccion,
             numero_direccion,
             piso,
             puerta,
             municipio,
             provincia,
             codigo_postal,
             movil,
             telefono,
             email,
             cuenta_bancaria)
VALUES     ('72303849Z',
            'Jose',
            'López Díaz',
            'Calle Bétis',
            6,
            0,
            '',
            'Sevilla',
            'Andalucía',
            41001,
            '+34694784087',
            '+34955738947',
            'jose.lopez@gmx.es',
            'ES6000491500051234567892');
INSERT INTO GESTOR_DATABASE.CLIENTES
            (numero_identificacion,
             nombre,
             apellidos,
             direccion,
             numero_direccion,
             piso,
             puerta,
             municipio,
             provincia,
             codigo_postal,
             movil,
             telefono,
             email,
             cuenta_bancaria)
VALUES     ('48945746K',
            'Isabel',
            'Martínez Perez',
            'Gran Vía',
            108,
            0,
            '',
            'Madrid',
            'Madrid',
            28001,
            '+34694784087',
            '+34955738947',
            'isabel87@hotmail.com',
            'ES9420805801101234567891');
INSERT INTO GESTOR_DATABASE.CLIENTES
            (numero_identificacion,
             nombre,
             apellidos,
             direccion,
             numero_direccion,
             piso,
             puerta,
             municipio,
             provincia,
             codigo_postal,
             movil,
             telefono,
             email,
             cuenta_bancaria)
VALUES     ('74849404K',
            'Manuel',
            'García Sánchez',
            'Calle de los Ciegos',
            20,
            0,
            '',
            'Jerez de la Frontera',
            'Andalucía',
            11401,
            '+34694784087',
            '+34955738947',
            'manuelito@gmail.com',
            '');
INSERT INTO GESTOR_DATABASE.CLIENTES
            (numero_identificacion,
             nombre,
             apellidos,
             direccion,
             numero_direccion,
             piso,
             puerta,
             municipio,
             provincia,
             codigo_postal,
             movil,
             telefono,
             email,
             cuenta_bancaria)
VALUES     ('88337746J',
            'Laura',
            'Romero Sosa',
            'Rúa do Franco',
            7,
            3,
            'b',
            'Santiago de Compostela',
            'Galicia',
            15701,
            '+34694784087',
            '+34955738947',
            '',
            '');
INSERT INTO GESTOR_DATABASE.CLIENTES
            (numero_identificacion,
             nombre,
             apellidos,
             direccion,
             numero_direccion,
             piso,
             puerta,
             municipio,
             provincia,
             codigo_postal,
             movil,
             telefono,
             email,
             cuenta_bancaria)
VALUES     ('83905867G',
            'Francisco',
            'Torres Álvarez',
            'Calle Larios',
            4,
            0,
            '',
            'Malaga',
            'Andalucía',
            29001,
            '+34694784087',
            '+34955738947',
            'francisco.torres@gmail.com',
            'ES7100302053091234567895');
INSERT INTO GESTOR_DATABASE.CLIENTES
            (numero_identificacion,
             nombre,
             apellidos,
             direccion,
             numero_direccion,
             piso,
             puerta,
             municipio,
             provincia,
             codigo_postal,
             movil,
             telefono,
             email,
             cuenta_bancaria)
VALUES     ('96867564M',
            'Ana',
            'Ruiz Ramirez',
            'Calle Alcalá',
            3,
            2,
            'a',
            'Madrid',
            'Madrid',
            28001,
            '+34694784087',
            '+34955738947',
            '',
            'ES1000492352082414205416');
INSERT INTO GESTOR_DATABASE.CLIENTES
            (numero_identificacion,
             nombre,
             apellidos,
             direccion,
             numero_direccion,
             piso,
             puerta,
             municipio,
             provincia,
             codigo_postal,
             movil,
             telefono,
             email,
             cuenta_bancaria)
VALUES     ('99588466F',
            'David',
            'Flores Benítez',
            'Paseo de Gracia',
            27,
            0,
            '',
            'Barcelona',
            'Cataluña',
            08001,
            '+34694784087',
            '+34955738947',
            'david.flores@outlook.es',
            'ES1720852066623456789011');
