INSERT INTO GESTOR_DATABASE.PROVEEDORES
            (numero_identificacion,
             nombre,
             apellidos,
             direccion,
             numero_direccion,
             piso,
             puerta,
             municipio,
             provincia,
             codigo_postal,
             movil,
             telefono,
             email,
             cuenta_bancaria)
VALUES     ('A15075062',
            'INDUSTRIA DE DISEÑO TEXTIL SA',
            '',
            'Avenida De La Diputación',
            3,
            0,
            '',
            'Arteixo',
            'La Coruña',
            15142,
            '',
            '+34981185400',
            '',
            '');
INSERT INTO GESTOR_DATABASE.PROVEEDORES
            (numero_identificacion,
             nombre,
             apellidos,
             direccion,
             numero_direccion,
             piso,
             puerta,
             municipio,
             provincia,
             codigo_postal,
             movil,
             telefono,
             email,
             cuenta_bancaria)
VALUES     ('A81948077',
            'ENDESA ENERGIA SA',
            '',
            'Calle Ribera Del Loira',
            60,
            0,
            '',
            'Madrid',
            'Madrid',
            28042,
            '',
            '+34912131000',
            '',
            '');
INSERT INTO GESTOR_DATABASE.PROVEEDORES
            (numero_identificacion,
             nombre,
             apellidos,
             direccion,
             numero_direccion,
             piso,
             puerta,
             municipio,
             provincia,
             codigo_postal,
             movil,
             telefono,
             email,
             cuenta_bancaria)
VALUES     ('B59088948',
            'PUNTO FA SL',
            '',
            'Calle Mercaders',
            9,
            0,
            '',
            'Palau-solita I Plegamans',
            'Barcelona',
            08184,
            '',
            '+34938602207',
            '',
            '');
INSERT INTO GESTOR_DATABASE.PROVEEDORES
            (numero_identificacion,
             nombre,
             apellidos,
             direccion,
             numero_direccion,
             piso,
             puerta,
             municipio,
             provincia,
             codigo_postal,
             movil,
             telefono,
             email,
             cuenta_bancaria)
VALUES     ('48945746K',
            'ZARA ESPAÑA SA',
            '',
            'Avenida De La Diputación ',
            0,
            0,
            '',
            'Arteixo',
            'La Coruña',
            15142,
            '',
            '+34900814676',
            '',
            '');
INSERT INTO GESTOR_DATABASE.PROVEEDORES
            (numero_identificacion,
             nombre,
             apellidos,
             direccion,
             numero_direccion,
             piso,
             puerta,
             municipio,
             provincia,
             codigo_postal,
             movil,
             telefono,
             email,
             cuenta_bancaria)
VALUES     ('A15108673',
            'PULL & BEAR ESPAÑA SA',
            '',
            'Avenida De La Diputación',
            20,
            0,
            '',
            'Arteixo',
            'La Coruña',
            15142,
            '',
            '+34900811822',
            '',
            '');
INSERT INTO GESTOR_DATABASE.PROVEEDORES
            (numero_identificacion,
             nombre,
             apellidos,
             direccion,
             numero_direccion,
             piso,
             puerta,
             municipio,
             provincia,
             codigo_postal,
             movil,
             telefono,
             email,
             cuenta_bancaria)
VALUES     ('B83875427',
            'PRIMARK TIENDAS SL',
            '',
            'Carretera Torrejón-ajalvir',
            0,
            0,
            '',
            'Barrio De El Castillo',
            'Madrid',
            15701,
            '',
            '+34916600186',
            '',
            '');
INSERT INTO GESTOR_DATABASE.PROVEEDORES
            (numero_identificacion,
             nombre,
             apellidos,
             direccion,
             numero_direccion,
             piso,
             puerta,
             municipio,
             provincia,
             codigo_postal,
             movil,
             telefono,
             email,
             cuenta_bancaria)
VALUES     ('A78276854',
            'BERSHKA BSK ESPAÑA SA',
            '',
            'Avenida Diputación',
            0,
            0,
            '',
            'Arteixo',
            'La Coruña',
            15142,
            '',
            '+34900456003',
            '',
            '');
INSERT INTO GESTOR_DATABASE.PROVEEDORES
            (numero_identificacion,
             nombre,
             apellidos,
             direccion,
             numero_direccion,
             piso,
             puerta,
             municipio,
             provincia,
             codigo_postal,
             movil,
             telefono,
             email,
             cuenta_bancaria)
VALUES     ('A59308114',
            'SAMSUNG ELECTRONICS IBERIA SA',
            '',
            'Avenida De Barajas',
            32,
            0,
            '',
            'Parque Empresarial La Moraleja',
            'Madrid',
            28108,
            '',
            '+34902879081',
            '',
            '');